# Generated by Django 2.2.1 on 2019-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeLoc',
            fields=[
                ('st_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='CONTENT_ID')),
                ('st_name', models.CharField(max_length=100, verbose_name='CONTENT_NM')),
                ('st_cradle', models.IntegerField(verbose_name='CRADLE_COUNT')),
                ('st_addr', models.CharField(max_length=300, verbose_name='ADDRESS')),
                ('st_lat', models.FloatField(verbose_name='LATITUDE')),
                ('st_lon', models.FloatField(verbose_name='LONGITUDE')),
                ('st_gu', models.CharField(max_length=20, verbose_name='ADDR_GU')),
            ],
            options={
                'verbose_name': 'Bike Station',
                'verbose_name_plural': 'Bike Stations',
                'ordering': ['st_id'],
            },
        ),
    ]
